# Generated by Django 6.0.2 on 2026-02-20 02:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailySales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True, verbose_name='Date')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='Nombre de commandes')),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Chiffre d'affaires")),
                ('total_discount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Remises totales')),
                ('average_order_value', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Panier moyen')),
                ('total_customers', models.PositiveIntegerField(default=0, verbose_name='Nombre de clients')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Vente journalière',
                'verbose_name_plural': 'Ventes journalières',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('order_created', 'Commande créée'), ('order_confirmed', 'Commande confirmée'), ('order_cancelled', 'Commande annulée'), ('invoice_created', 'Facture créée'), ('table_status_changed', 'Statut de table modifié'), ('reservation_created', 'Réservation créée'), ('reservation_confirmed', 'Réservation confirmée'), ('reservation_cancelled', 'Réservation annulée'), ('user_login', 'Connexion utilisateur'), ('user_logout', 'Déconnexion utilisateur'), ('menu_item_added', 'Plat ajouté'), ('menu_item_updated', 'Plat modifié')], max_length=30, verbose_name='Action')),
                ('description', models.TextField(verbose_name='Description')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Adresse IP')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': "Journal d'activité",
                'verbose_name_plural': "Journaux d'activité",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('stock_low', 'Stock faible'), ('stock_critical', 'Stock critique'), ('reservation_upcoming', 'Réservation à venir'), ('table_long_occupied', 'Table occupée longtemps'), ('order_delayed', 'Commande en retard'), ('system_error', 'Erreur système')], max_length=30, verbose_name="Type d'alerte")),
                ('priority', models.CharField(choices=[('low', 'Basse'), ('medium', 'Moyenne'), ('high', 'Haute'), ('critical', 'Critique')], default='medium', max_length=10, verbose_name='Priorité')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('message', models.TextField(verbose_name='Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='Résolu')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Résolu le')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL, verbose_name='Résolu par')),
            ],
            options={
                'verbose_name': 'Alerte système',
                'verbose_name_plural': 'Alertes système',
                'ordering': ['-created_at'],
            },
        ),
    ]
