# Generated by Django 6.0.2 on 2026-02-20 01:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('icon', models.CharField(blank=True, help_text="Classe d'icône Bootstrap (ex: bi-cup-hot)", max_length=50, null=True, verbose_name='Icône')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du plat')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix (MAD)')),
                ('image', models.ImageField(upload_to='menu_items/', verbose_name='Image du plat')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('prep_time', models.PositiveIntegerField(default=15, help_text='Temps de préparation en minutes', verbose_name='Temps de préparation (min)')),
                ('allergens', models.CharField(blank=True, help_text='Ex: Gluten, Lactose, Fruits à coque', max_length=255, null=True, verbose_name='Allergènes')),
                ('is_spicy', models.BooleanField(default=False, verbose_name='Plat épicé')),
                ('is_vegetarian', models.BooleanField(default=False, verbose_name='Végétarien')),
                ('is_vegan', models.BooleanField(default=False, verbose_name='Végan')),
                ('calories', models.PositiveIntegerField(blank=True, null=True, verbose_name='Calories')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Plat',
                'verbose_name_plural': 'Plats',
                'ordering': ['category', 'name'],
            },
        ),
    ]
