# Generated by Django 6.0.2 on 2026-02-20 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Numéro de table')),
                ('capacity', models.PositiveIntegerField(default=2, verbose_name='Capacité')),
                ('status', models.CharField(choices=[('available', 'Disponible'), ('occupied', 'Occupée'), ('reserved', 'Réservée'), ('out_of_order', 'Hors service')], default='available', max_length=20, verbose_name='Statut')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='Emplacement')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'ordering': ['number'],
            },
        ),
    ]
