# Generated by Django 6.0.2 on 2026-02-20 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='location',
        ),
        migrations.AddField(
            model_name='table',
            name='zone',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Zone'),
        ),
    ]
