# Generated by Django 6.0.2 on 2026-02-20 02:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_remove_table_location_table_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['zone', 'number'], 'verbose_name': 'Table', 'verbose_name_plural': 'Tables'},
        ),
        migrations.AddField(
            model_name='table',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création'),
        ),
        migrations.AddField(
            model_name='table',
            name='description',
            field=models.TextField(blank=True, help_text='Ex: Près de la fenêtre, vue sur le jardin', null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='table',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='table',
            name='position_x',
            field=models.FloatField(blank=True, help_text='Position horizontale sur le plan de salle', null=True, verbose_name='Position X'),
        ),
        migrations.AddField(
            model_name='table',
            name='position_y',
            field=models.FloatField(blank=True, help_text='Position verticale sur le plan de salle', null=True, verbose_name='Position Y'),
        ),
        migrations.AddField(
            model_name='table',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification'),
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)], verbose_name='Capacité (personnes)'),
        ),
        migrations.AlterField(
            model_name='table',
            name='status',
            field=models.CharField(choices=[('available', 'Libre'), ('occupied', 'Occupée'), ('reserved', 'Réservée'), ('cleaning', 'En nettoyage'), ('out_of_service', 'Hors service')], default='available', max_length=20, verbose_name='Statut'),
        ),
        migrations.AlterField(
            model_name='table',
            name='zone',
            field=models.CharField(choices=[('main_hall', 'Salle principale'), ('terrace', 'Terrasse'), ('private_room', 'Salon privé'), ('bar', 'Bar'), ('vip', 'VIP')], default='main_hall', max_length=20, verbose_name='Zone'),
        ),
        migrations.CreateModel(
            name='TableMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la fusion')),
                ('total_capacity', models.PositiveIntegerField(default=0, verbose_name='Capacité totale')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('tables', models.ManyToManyField(related_name='merges', to='tables.table', verbose_name='Tables fusionnées')),
            ],
            options={
                'verbose_name': 'Fusion de tables',
                'verbose_name_plural': 'Fusions de tables',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('customer_phone', models.CharField(max_length=15, verbose_name='Téléphone')),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('num_guests', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Nombre de personnes')),
                ('date', models.DateField(verbose_name='Date de réservation')),
                ('time', models.TimeField(verbose_name='Heure de réservation')),
                ('duration_minutes', models.PositiveIntegerField(default=120, verbose_name='Durée estimée (minutes)')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('confirmed', 'Confirmée'), ('cancelled', 'Annulée'), ('completed', 'Terminée'), ('no_show', 'Non présenté')], default='pending', max_length=15, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, help_text='Allergies, occasions spéciales, etc.', null=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Date de modification')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Confirmée le')),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_confirmed', to=settings.AUTH_USER_MODEL, verbose_name='Confirmée par')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations_created', to=settings.AUTH_USER_MODEL, verbose_name='Créée par')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='tables.table', verbose_name='Table')),
            ],
            options={
                'verbose_name': 'Réservation',
                'verbose_name_plural': 'Réservations',
                'ordering': ['date', 'time'],
                'unique_together': {('table', 'date', 'time')},
            },
        ),
    ]
